[package]
name = "safe-condvar"
version = "0.1.0"
authors = ["Mateus CorrÃªa <mateus.correa@lsbd.ufc.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
